### ISSUE TITLE
Highradius Source Code Data Leakage | Action Needed ASAP

### ISSUE THREAD

**Issue by Ranjit-Chigurupati** [nooobcoder/HighRadiusTraining#42]
Hi nooobcoder,

We identified that one of your GitHub public Repositories “[HighRadiusTraining](https://github.com/nooobcoder/HighRadiusTraining)” contains a source code which is related/owned by the Highradius. Please Delete/remove the respective data from the public exposure, if not this will be considered as a Copyright Violation and necessary action will be taken.

Any data that is related/owned by the Highradius Corporation should not be used for your personal benefits or should not exposed in to the public. Any such unauthorized activities will be considered as series offence and necessary legal actions will be taken.

Thanks & Regards,
Ranjit Kumar Chigurupati,
Led Information Security Engineer,
Highradius Corporation.

**Comment by nooobcoder** [comment]
Closed as irrelevant, and targeting data that was for training purposes, as no real company data was consumed in the project.
All data used in the project is for demo purposes only.

Kindly convey message to conduct fair selection process, otherwise return actions would be issued for cheating students with unfair means.

Thank You,
@nooobcoder
